name: CI/CD Flask SPA to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # -------- BACKEND DEPLOYMENT --------
    - name: Deploy Flask Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: Backenddeb
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: backend

    # -------- FRONTEND DEPLOYMENT --------
    - name: Deploy Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: frontendweb1
        publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
        package: frontend
